name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step two
              run: printf "%s\n" "$now"
    job2:
        name: Second Job
        needs: job1
        runs-on: windows-latest
        steps:
            - name: Step three
              run: echo $(date+"%x")

           


         
